# Copyright (c) 2020 Red Hat, Inc.

os:
  - linux

language: go
go:
  - 1.13.x

services:
  - docker

addons:
  sonarcloud:
    organization: "open-cluster-management"
    token:
      secure: "BILrgWZsb9Cif37JShJAsxoZNG43EqRJImbijWQBJ0axX4uLziNHM52pPQfKULN3V2n6Ncqh0uCmn0DYlT6XR3ovy7RjNWkOm6AXd1J6p92x8/AFpK6xxq+/fs2QY6cpdfH/H6bYihPc/m1w52e7qDWMAr5XYG1NEZFS9056WvRnmkRPVQkx/iZIjQyfucdL3DXWNZnEUZLXCA055w8ngXTrjfESMHpDPJtGmxhyeTsWFqTv9hojKSpmc8kiGBJgNJBmDwpAItSDaNSN+vW4B7+aTEun9eCeBvBEldiizzBL3pPKEPqJz8Q5BPFaduxAPfHxHHUTWdMI/QvDbn+1Hlr59N6Ch9J/TDgzb8mnsjVAYeQBOf8oZnqzsmhAaTqArOIR5eB4JainFP5C2TM4ARo4dJozTx248dZ0bI74zvuA0phDibW+FapafZcbzXo2RES/mMqFCzerBUpOvThMBG/gM4C4G3OBTmaH9CMPBzcY0XaJvA2X/XfybAIk0SCXPIEcMGYHIPAxEz/SpKMrpRtp3FBiO58RP+IJsJIobWAFPcRt01a+1v9EEe7ENSXF6mO5oaTFqVlnjy0I0CaF5LndqQWhwffUP/PI42nvylk52O9Q2iN4XFjfnymwPIu+hZG6O8MoMhZheZqD4SvO3LrzrHj1OiMUwlQQuN7CKAc="

branches:
  only:
    - main
    - /^release-[0-9]+\..*$/

env:
  global:
    # Required
    - OS=linux
    - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"

    # Component Specific 
    - COMPONENT_DEPLOY_COMMAND=${TRAVIS_BUILD_DIR}/cicd-scripts/deploy-to-cluster.sh
    - COMPONENT_INIT_COMMAND=${TRAVIS_BUILD_DIR}/cicd-scripts/install-dependencies.sh
    - COMPONENT_BUILD_COMMAND=${TRAVIS_BUILD_DIR}/cicd-scripts/build.sh
    - COMPONENT_UNIT_TEST_COMMAND=${TRAVIS_BUILD_DIR}/cicd-scripts/run-unit-tests.sh
    - COMPONENT_E2E_TEST_COMMAND=${TRAVIS_BUILD_DIR}/cicd-scripts/run-e2e-tests.sh

    - GO111MODULE=on

stages:
  - build
  - unit-test
  - test-e2e
  - release-ff
  - publish

before_script:
  # Bootstrap the build harness.
  - make init
  - git config --global credential.helper store
  - echo "https://${GITHUB_TOKEN}:x-oauth-basic@github.com" >> ~/.git-credentials
  # Set the image tag differently for PRs.
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
  # Use ssh to pull from private repos.
  - git config --global url."git@github.com:".insteadOf "https://github.com/"

jobs:
  include:
    - stage: build
      name: "Build the test image, push it, check potential leaked credentials and check image security scan status"
      script:
        - make component/build
        - make component/push
        - make security/scans
    - stage: unit-test
      name: "Run unit tests"
      script:
        # Set the image tag differently for PRs
        # Bootstrap the build harness, pull test image, and run unit tests.   
        - make component/pull
        - make component/test/unit
        - make sonar/go
        # sonar-scanner --debug
    - stage: test-e2e
      name: "Deploy the image to a cluster and run e2e tests"
      script:
        #Check out a clusterpool, set up oc, deploy, run e2e tests, and return clusterpool cluster 
        - make component/pull
        - make component/test/e2e
    - stage: release-ff
      name: "Push commits from main to branch defined in RELEASE_FF_BRANCH"
      if: type = push AND branch =~ /^main$/
      script:
        - make release-ff
    - stage: publish
      name: "Publish the image to quay with an official version/sha tag and publish entry to integration pipeline stage"
      if: type = push AND branch =~ /^release-[0-9]+\..*$/
      script:
        - make pipeline-manifest/update PIPELINE_MANIFEST_COMPONENT_SHA256=${TRAVIS_COMMIT} PIPELINE_MANIFEST_COMPONENT_REPO=${TRAVIS_REPO_SLUG} PIPELINE_MANIFEST_BRANCH=${TRAVIS_BRANCH}
